- 10. Hablando de pilotos de carreras
    
    ### **Contexto:**
    
    Eres un ingeniero de datos en un equipo de Fórmula 1 y debes analizar el rendimiento de **10 pilotos** en **5 carreras**. Para ello, trabajarás con matrices en NumPy para transformar los datos y extraer información útil.
    
    ### **Tareas:**
    
    1. **Representar los datos** en un array bidimensional de NumPy donde cada fila sea un piloto y cada columna una carrera.

In [84]:
import numpy as np

# Datos de entrada
pilotos = np.random.randint(
    1, 10, [10, 5]
)  # Matriz 5x10 aleatoria donde las filas son los pilotos y las columnas las posiciones de cada carrera
print("Pilotos:\n ", pilotos)
print("----------------------------")


Pilotos:
  [[9 6 6 6 2]
 [8 3 1 9 4]
 [4 5 1 9 3]
 [5 7 7 2 9]
 [9 8 6 5 3]
 [4 9 3 6 8]
 [5 5 5 7 7]
 [3 4 7 4 8]
 [4 3 9 8 5]
 [8 1 8 9 9]]
----------------------------


2. **Transformación de arrays:**
        - Reorganiza la matriz con `.reshape()` para analizar los datos de otra manera.
        - Usa `.ravel()` o `.flatten()` para convertir la matriz en un array 1D.

In [85]:
# Aplicamos .reshape() y cambiamos el forma del array
pilotos_reorganizado = pilotos.reshape(5, 10)
print("Pilotos reorganizado:\n", pilotos_reorganizado)
print("----------------------------")

# Aplicamos .ravel() y convertimos en array en 1D
pilotos_aplanado = pilotos.flatten()
print("Pilotos aplanado:\n", pilotos_aplanado)
print("----------------------------")

Pilotos reorganizado:
 [[9 6 6 6 2 8 3 1 9 4]
 [4 5 1 9 3 5 7 7 2 9]
 [9 8 6 5 3 4 9 3 6 8]
 [5 5 5 7 7 3 4 7 4 8]
 [4 3 9 8 5 8 1 8 9 9]]
----------------------------
Pilotos aplanado:
 [9 6 6 6 2 8 3 1 9 4 4 5 1 9 3 5 7 7 2 9 9 8 6 5 3 4 9 3 6 8 5 5 5 7 7 3 4
 7 4 8 4 3 9 8 5 8 1 8 9 9]
----------------------------


**3. Operaciones aritméticas:**
 - Calcula el promedio de posiciones por piloto y por carrera (`axis=0` y `axis=1`).
- Aplica una penalización sumando un valor a cada posición y recalculando los valores.

In [86]:
# Calculamos el promedio de las posiciones por piloto (FILA)
promedios_pilotos = np.mean(pilotos, axis=1)
for i in range(len(promedios_pilotos)):
    print(f"Promedio piloto {i + 1}: {promedios_pilotos[i]}")
print("----------------------------")

# Calculamos el promedio de las posiciones por carrera (COLUMNAS)
promedios_carreras = np.mean(pilotos, axis=0)
for i in range(len(promedios_carreras)):
    print(f"Promedio carrera {i + 1}: {promedios_carreras[i]}")
print("----------------------------")

# Calculamos el promedio de las posiciones por piloto con penalización de +1 (FILA)
pilotos_penalizado = pilotos + 1
promedios_pilotos_penalizado = np.mean(pilotos_penalizado, axis=1)
for i in range(len(promedios_pilotos_penalizado)):
    print(f"Promedio piloto penalizado {i + 1}: {promedios_pilotos_penalizado[i]}")
print("----------------------------")

# Calculamos el promedio de las posiciones por carrera con penalización de +1 (COLUMNAS)
promedios_carreras_penalizadas = np.mean(pilotos_penalizado, axis=0)
for i in range(len(promedios_carreras_penalizadas)):
    print(f"Promedio carrera penalizada {i + 1}: {promedios_carreras_penalizadas[i]}")
print("----------------------------")

Promedio piloto 1: 5.8
Promedio piloto 2: 5.0
Promedio piloto 3: 4.4
Promedio piloto 4: 6.0
Promedio piloto 5: 6.2
Promedio piloto 6: 6.0
Promedio piloto 7: 5.8
Promedio piloto 8: 5.2
Promedio piloto 9: 5.8
Promedio piloto 10: 7.0
----------------------------
Promedio carrera 1: 5.9
Promedio carrera 2: 5.1
Promedio carrera 3: 5.3
Promedio carrera 4: 6.5
Promedio carrera 5: 5.8
----------------------------
Promedio piloto penalizado 1: 6.8
Promedio piloto penalizado 2: 6.0
Promedio piloto penalizado 3: 5.4
Promedio piloto penalizado 4: 7.0
Promedio piloto penalizado 5: 7.2
Promedio piloto penalizado 6: 7.0
Promedio piloto penalizado 7: 6.8
Promedio piloto penalizado 8: 6.2
Promedio piloto penalizado 9: 6.8
Promedio piloto penalizado 10: 8.0
----------------------------
Promedio carrera penalizada 1: 6.9
Promedio carrera penalizada 2: 6.1
Promedio carrera penalizada 3: 6.3
Promedio carrera penalizada 4: 7.5
Promedio carrera penalizada 5: 6.8
----------------------------


4. **Producto escalar:**
- Modela el rendimiento de dos pilotos como vectores y calcula su similitud mediante el **producto escalar**.

In [87]:
# Para calcular la similitud entre dos vectores (pilotos) debemos calcular la formula: similitud = p_escalar / (L2_array1 * L2_array2). El resultado es un número del 0 al 1 significando el valor 0 que los vectores son completamente opuestos y 1 que son iguales.
array_piloto1 = pilotos[0, :]
array_piloto2 = pilotos[1, :]
producto_escalar = np.dot(array_piloto1, array_piloto2)
piloto1_L2 = np.linalg.norm(array_piloto1)
piloto2_L2 = np.linalg.norm(array_piloto2)
similitud = producto_escalar / (piloto1_L2 * piloto2_L2)
print(f"Similitud entre los dos primeros pilotos:  {similitud:.3f}")

Similitud entre los dos primeros pilotos:  0.870


5. **Producto cruzado:**
- Representa las posiciones de dos pilotos en las primeras tres carreras como vectores 3D y calcula su **producto cruzado**, interpretando el resultado en términos de diferencias de rendimiento.

In [100]:
# Calcular el producto cruzado de los dos primeros pilotos en las primeras tres carreras
producto_cruzado = np.cross(pilotos[0,:3], pilotos[1,:3])
print("Producto cruzado: ", producto_cruzado)

Producto cruzado:  [-12  39 -21]



6. **Extra bonus:**
- Normaliza los datos usando la **norma L2** (`np.linalg.norm()`) para comparar el rendimiento de los pilotos en diferentes circuitos.

In [99]:
# Calculamos la magnitud del array para calcular la normalizacion de los datos
magnitud = np.linalg.norm(pilotos)
pilotos_normalizados = pilotos / magnitud
print("Pilotos normalizados:\n", pilotos_normalizados)

Pilotos normalizados:
 [[0.20443988 0.13629326 0.13629326 0.13629326 0.04543109]
 [0.18172434 0.06814663 0.02271554 0.20443988 0.09086217]
 [0.09086217 0.11357771 0.02271554 0.20443988 0.06814663]
 [0.11357771 0.1590088  0.1590088  0.04543109 0.20443988]
 [0.20443988 0.18172434 0.13629326 0.11357771 0.06814663]
 [0.09086217 0.20443988 0.06814663 0.13629326 0.18172434]
 [0.11357771 0.11357771 0.11357771 0.1590088  0.1590088 ]
 [0.06814663 0.09086217 0.1590088  0.09086217 0.18172434]
 [0.09086217 0.06814663 0.20443988 0.18172434 0.11357771]
 [0.18172434 0.02271554 0.18172434 0.20443988 0.20443988]]
