# 11. Ejercicio de investigación de Numpy
- ¿Qué es NumPy y para qué se utiliza en programación científica?<br>
    - NumPy (Numerical Python) es una biblioteca de Python esencial para realizar cálculos numéricos, facilita el trabajo con datos numéricos y
simplifica la realización de cálculos matemáticos complejos. Sus aplicaciones incluyen: 
        - Álgebra lineal
        - Análisis estadístico
        - Generación de números aleatorios
        - Operaciones con matrices
        - Interfaz de bajo nivel para operaciones de alto rendimiento y compatibilidad con bibliotecas de C/C++
<br><br>
- Historia de Numpy
    - NumPy fue creado en 2005 por Travis Oliphant, un científico e ingeniero de software que buscaba
una solución más eficiente y flexible para realizar cálculos numéricos en Python.
<br><br>
- ¿Cuál es la diferencia entre una lista de Python y un array de NumPy?
    - Ambos sirven para almacenar colecciones de elemntos, pero tienen unas diferencias muy marcadas:
        - Homogeneidad de tipos de datos: Los elementos de un array en Numpy deben ser todos del mismo tipo, mientras que las colecciones de python pueden contener variaciones entre estos.
        - Rendimiento: Los arrays de Numpy estan diseñados para trabajar en memoria y optimizar operaciones numéricas por lo que tienen mejor rendimiento, al contrario que las colecciones de python que son mas generales y no poseen optimizacion.
        - Operaciones matemáticas y de algébra lineal: NumPy proporciona multitud de funciones matemáticas, álgebra lineal y manipulación de arrays las cuales no estan disponibles en python.
        - Tamaño: El tamaño de los arrays de Numpy es fijo en el momento de su creación, por otro lado los de python son dinámicos.
        - Memoria: Los arrays de Numpy al tener un tamaño fijo, su estructura es mas compacta por lo que ocupa menos espacio en memoria siendo mas eficientes en la misma.

- ¿Cómo se crea un array en NumPy? <br>
Para crear arrays en NumPy primero deberemos instalar la librería en nuestro entorno Python, importarla al archivo donde vayamos a utilizarla y finalmente mediante la función numpy.array() lo podremos crear pasando tantas listas anidadas como dimensiones queramos. <br>
Explicar y dar ejemplos de:
    - Un array unidimensional.
    - Un array bidimensional.
    - Un array de valores inicializados con ceros, unos y valores aleatorios.

In [2]:
# Importamos la librería NumPy
import numpy as np

# Creamos un array unidimensional de enteros pasandole unicamente una lista de valores
array_1d = np.array([1, 2, 3, 4, 5])
print("Array 1D: ", array_1d)

# Creamos un array bidimensional de 2 filas y 5 columnas
array_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("Array 2D: \n", array_2d)

# Creamos un array de valores incializados a ceros mediante la función .zeros() el cual como parámetro acepta el tamaño del array a crear. En este caso la pasamos una tupla para que nos cree un array de 2x3
array_zeros = np.zeros((2, 3))
print("Array zeros:\n ", array_zeros)

# Para crear un array de valores a 1 se utiliza un método parecido al de ceros pero con la función .ones(), pasandole una tupla creamos un array de 3x3
array_unos = np.ones((3,3))
print("Array unos:\n ", array_unos)

# Creamos un array de valores aleatorios mediante la función arange() la cual pasandole como parámetros el límite superior e inferior de los números a introducir lo creará.
# Tambiémn mediante el parámetro 'size' podemos definir el tamaño para dicho array.
array_aleatorios = np.random.randint(0, 11, size=(2,3))
print("Array aleatorio:\n", array_aleatorios)



Array 1D:  [1 2 3 4 5]
Array 2D: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array zeros:
  [[0. 0. 0.]
 [0. 0. 0.]]
Array unos:
  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array aleatorio:
 [[ 9  4  8]
 [ 9  5 10]]


- ¿Cómo acceder a los elementos de un array y cómo modificar sus valores?
Para acceder a los elementos de un array contamos con dos técnicas parecidas pero que sirven para obtener resultados diferentes. 
    -   Por un lado está la 'indexación' la cual nos permite acceder a un solo elemento del array en una posición específica, su sintaxis varía en función de las dimensiones del array. Ejemplo, para acceder al elemento de la fila 2 columna 4 en una matriz de 5x5 la sintaxis sería la siguiente: nombre_array[1,3] (Hay que tener en cuenta que la indexación de Numpy empieza por 0).
    -   Por otro lado tenemos el Slicing el cual nos sirve para obtener rangos de valores y no solo un rango solo. Para cada dimensión su sintaxis sería 'inicio:fin:paso'. Imaginemos que queremos obtener unicamente la columna 3 de todas nuestras filas en una matriz de 5x5, se haría de la siguiente manera: nombre_array[:,2] (El caracter ':' significa que obtenemos todo el rango, en nuestro caso las filas)
    -   Finalmente para modificar los valores de un array habría primeramente que obtener la posición a modificar mediante indexación y seguidamente añadir una igualación con el valor que queramos intercambiar. 

In [12]:
# Declaramos nuestra matriz de ejemplo de 3x3
matriz = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Mediante indexación obtenemos el valor ubicado en la tercera fila primera columna.
valor = matriz[2,0]
print("Valor de la fila 3 columna 1: ", valor)

# Mediante Slicing obtenemos la columna 2 de todas las filas
columna = matriz[:,1]
print("Segunda columna de la matriz:\n", columna)

# Vamos a modificar el valor de la fila 3 columna 1 obtenido anteriormente (Era 7)
matriz[2,0] = 12 # Ahora pasa a ser igual a 12
print("Valor de la fila 3 columna 1 modificado: ", matriz[2,0])


Valor de la fila 3 columna 1:  7
Segunda columna de la matriz:
 [2 5 8]
Valor de la fila 3 columna 1 modificado:  12


- ¿Qué son los **ejes (axis)** en un array multidimensional? Explica con ejemplos prácticos.<br>
Los ejes 'axis' en NumPy hacen refenrencia a las filas y a las columnas de un array bidimensional (matriz). Este se pasa como parámetro a las funciones que realizan operaciones sobre los arrays indicando así donde queremos que haga efecto esta operación, puede obtener dos valores diferentes:
    - `axis=0`  → Operación colapsa filas, es decir, actúa sobre las columnas.
    - `axis=1`  → Operación colapsa columnas, es decir, actúa sobre las filas. (Este es el valor por defecto del parámetro en la mayoría de las funciones).

In [16]:
# Definimos nuestro array bidimensional de ejemplo de 3x3
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

# Realizamos la operación sum sobre el array aplicando axis = 1 y axis = 0
suma_filas = array_2d.sum(axis = 1)
suma_columnas = array_2d.sum(axis = 0)
print("Suma de filas aplicando 'axis = 1': ", suma_filas)
print("Suma de columnas aplicando 'axis = 0': ", suma_columnas)

Suma de filas aplicando 'axis = 1':  [ 6 15 24]
Suma de columnas aplicando 'axis = 0':  [12 15 18]


- Explica la diferencia entre **np.dot()** (producto escalar) y **np.cross()** (producto cruzado).
    -   El producto escalar (np.dot) es una operación que multiplica los elementos correspondientes de dos vectores de cualquier tamaño y luego suma los resultados. El resultado es un numero entero (escalar) el cual es utilizado en álgebra lineal, procesamiento de señales y evaluación de la similitud entre vectores.
    -   El producto cruzado (np.cross) entre dos vectores en 3 dimensiones produce un tercer vector el cual es perpendicular a los dos primeros, la magnitud del vector resultante es igual al área del paralelogramo formado por los otros dos primeros. Unicamente puede aplicarse a vectores definimos en 3D, para calcular los 3 valores del vector resultante se multiplica en cruz las columnas ajenas a la que se quiere hallar y luego se restan; realiando esta operación 3 veces en las diferenetes columnas. Esta operación se utiliza física, ingeniería y gráficos por computadora.

- ¿Cómo se pueden transformar las dimensiones de un array? Explica con ejemplos las funciones `reshape()` y `flatten()`.
NumPy cuenta con diversas funciones las cuales nor permiten redimensionar array ya creados:
    -   `reshape()`: Funciona pasando como parametro las dimensiones separadas por comas del array al que queremos redimensionar el original. Solo puede pasarse una combinación de dimensiones válida para el número de componentes del array, es decir, si tenemos una array 1D de 12 elementos y queremos convertirlo en un array 2D las únicas combinaciones posibles serían 6x2, 2x6, 4x3, 3x4.
    -   `flatten()`: Devuelve una copia del array al que se le aplica un redimensionado a 1D ('aplanado').

In [19]:
# Declaramos un vector 1D de 10 elementos
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mediante rashape() lo transformamos en una matriz de 2x5
matriz = vector.reshape(2,5)
print("Vector redimensionado a matriz:\n", matriz)

# Aplanamos la matriz para volver al vector original mediante flatten()
aplanado = matriz.flatten()
print("Matriz aplanada: ", aplanado)

Vector redimensionado a matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Matriz aplanada:  [ 1  2  3  4  5  6  7  8  9 10]


- ¿Qué es Matplotlib y en qué situaciones se usa en programación? <br>
Se trata de una biblioteca de Python open source que se emplea para la visualización de datos. Tiene a su disposición la creación de infinidad de gráficos tanto en 2D como en 3D diferentes como  de barras, mapas de calor, roscos...
En programación se utiliza sobretodo en el campo del Data Science y el Machine Learning, donde resulta indispensable para tener una buena visualización de los datos combinado con otras librerías como Numpy o Pandas.