- Gestión sistemas de inventario de una tienda
    
    **Objetivo:** Utilizar arrays en `NumPy` para gestionar y analizar un sistema de inventario de una tienda. Practicarás la creación de arrays de diferentes dimensiones y tipos, y manipularás datos relacionados con los productos de una tienda.
    
    **Escenario:** Imagina que eres el encargado de gestionar el inventario de una tienda de electrónica. La tienda tiene diferentes productos, y necesitas hacer un seguimiento de las cantidades disponibles, los precios y las categorías de productos. Utilizarás `NumPy` para organizar esta información.
    
    ---
    
    ### Tareas:
    
    1. **Crear un array unidimensional con el nombre de los productos:** Tienes una lista de 5 productos: `"Smartphone"`, `"Tablet"`, `"Laptop"`, `"Auriculares"`, `"Teclado"`. Imprímelo.
    2. **Crear un array bidimensional con la cantidad en stock de cada producto:** La tienda tiene el siguiente stock de productos:
        
        ```bash
        Smartphone - 50
        Tablet - 30
        Laptop - 15
        Auriculares - 40
        Teclado - 60
        ```
        
        Crea un array bidimensional donde cada fila represente un producto y las columnas representen el stock disponible en diferentes almacenes. Imprime el array.
        
    3. **Crear un array tridimensional para registrar las ventas de cada producto durante una semana:** Imagina que tienes un registro de ventas para cada uno de los 5 productos durante 3 días de la semana. Cada capa del array representará un día de ventas y las columnas serán las cantidades vendidas para cada producto:
        
        ```bash
        Día 1: [5, 3, 2, 6, 4]
        Día 2: [7, 4, 1, 8, 5]
        Día 3: [6, 2, 3, 5, 4]
        ```
        
        Crea un array tridimensional que almacene esta información. Imprímelo.
        
    4. **Crear un array de ceros para los productos no vendidos hoy:** Los productos que no se han vendido hoy deben estar en cero. Crea un array de ceros para representar la cantidad de productos no vendidos de la tienda hoy. Imprime el array.
    5. **Crear un array de unos para los productos que están en promoción:** Los productos en promoción tienen un valor de `1`, mientras que los que no están en promoción tienen `0`. Crea un array de unos y ceros, donde los productos en promoción tienen el valor `1`. Los productos en promoción son el `"Smartphone"` y el `"Teclado"`. Imprímelo.
    6. **Crear un array con un rango de precios de productos:** La tienda tiene productos cuyo precio varía entre 50 y 1000 unidades monetarias. Crea un array con los precios de los productos, usando la función `np.arange`, y un paso de 50 unidades. Imprímelo.
    7. **Crear un array de precios aleatorios:** Crea un array con precios aleatorios para los productos entre 100 y 500 unidades monetarias, de tamaño 5. Imprímelo.
    8. **Generar un array de números enteros aleatorios para la cantidad vendida:** Utiliza `np.random.randint` para crear un array de 5 elementos, con valores aleatorios entre 1 y 10, que representen las unidades vendidas de cada producto hoy. Imprímelo.
    9. **Crear un array vacío para almacenar los valores de descuento:** Crea un array vacío de tamaño 5x1 para almacenar los descuentos que se aplicarán a cada producto. Imprímelo.
    10. **Generar un array con valores espaciados para analizar el cambio en las ventas:** Imagina que deseas analizar cómo cambian las ventas en diferentes intervalos de tiempo (por ejemplo, cada 2 horas). Utiliza `np.linspace`para generar un array con 5 puntos de venta, distribuidos entre 0 y 1000 unidades, representando las ventas totales del día. Imprímelo.

In [12]:
# Importamos la biblioteca de Numpy
import numpy as np

# Crear array unidimensional con los productos disponibles en la tienda
productos = np.array(["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"])
print("Productos: ", productos)

# Crear array bidimensional con los productos y cantidades de los mismos
cantidad = np.array(
    [
        ["Smartphone", 50],
        ["Tablet", 30],
        ["Laptop", 15],
        ["Auriculares", 40],
        ["Teclado", 60],
    ]
)
print("Cantidad:\n ", cantidad)

# Crear un array tridimensional para registrar las ventas de cada producto durante una semana
ventas = np.array(
    [
        [[5, 3, 2, 6, 4]],
        [[7, 4, 1, 8, 5]],
        [[6, 2, 3, 5, 4]],
        [[5, 3, 5, 4, 7]],
        [[1, 4, 5, 9, 7]],
        [[2, 5, 4, 3, 1]],
        [[2, 4, 5, 1, 2]],
    ]
)
print("Ventas: ", ventas)

# Crear un array de ceros para los productos no vendidos hoy
ceros = np.zeros((1, 5))
print("Ceros: ", ceros)

# Crear un array de unos para los productos que están en promoción (1 es en promocion 0 es que no)
promocion = np.array([1, 0, 0, 0, 1])
print("Promocion: ", promocion)

# Crear un array con un rango de precios de productos
precios = np.arange(50, 1001, 50)
print("Precios: ", precios)

# Crear un array de precios aleatorios entre 100 y 500 de tamaño 5
random_prices = np.array([54, 67, 98, 76, 89])
print("Precios aleatorios: ", random_prices)

# Generar un array de números enteros aleatorios para la cantidad vendida
generated_random_prices = np.random.randint(1, 10, size=(5))
print("Precios aleatorios generados: ", generated_random_prices)

# Crear un array vacío para almacenar los valores de descuento
empty = np.empty(5)
print("Vacio: ", empty)

# Generar un array con valores espaciados para analizar el cambio en las ventas
espaciado = np.linspace(0, 1000, 5)
print("Espaciado: ", espaciado)

Productos:  ['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
Cantidad:
  [['Smartphone' '50']
 ['Tablet' '30']
 ['Laptop' '15']
 ['Auriculares' '40']
 ['Teclado' '60']]
Ventas:  [[[5 3 2 6 4]]

 [[7 4 1 8 5]]

 [[6 2 3 5 4]]

 [[5 3 5 4 7]]

 [[1 4 5 9 7]]

 [[2 5 4 3 1]]

 [[2 4 5 1 2]]]
Ceros:  [[0. 0. 0. 0. 0.]]
Promocion:  [1 0 0 0 1]
Precios:  [  50  100  150  200  250  300  350  400  450  500  550  600  650  700
  750  800  850  900  950 1000]
Precios aleatorios:  [54 67 98 76 89]
Precios aleatorios generados:  [7 9 1 5 7]
Vacio:  [2.67e-322 3.31e-322 4.84e-322 3.75e-322 4.40e-322]
Espaciado:  [   0.  250.  500.  750. 1000.]
