- 3. Indexación y selección en arrays con Numpy
    
    En este ejercicio, trabajarás con arrays 1D y 2D en NumPy, aplicando indexación y selección de elementos.
    
    ### Tareas:
    
    1. **Creación de arrays**
        - Crea un array **1D** con los números del **1 al 10** utilizando `np.arange()`.
        - Crea un array **2D** de tamaño **3x3** con valores del **1 al 9** utilizando `np.arange()` y `.reshape()`.
    2. **Indexación en arrays**
        - Extrae y muestra:
            - El primer y último elemento del array 1D.
            - El primer elemento de la primera fila del array 2D.
            - El último elemento de la última fila del array 2D.
            - El elemento ubicado en la segunda fila y tercera columna del array 2D.
    3. **Selección de filas y columnas**
        - Extrae y muestra:
            - La primera fila completa del array 2D.
            - La segunda columna completa del array 2D.

In [15]:
import numpy as np

# Crea un array **1D** con los números del **1 al 10** utilizando `np.arange()`.
array_1d = np.arange(1, 11)
print("Array unidimensional del 1 al 10: ", array_1d)

# Crea un array **2D** de tamaño **3x3** con valores del **1 al 9** utilizando `np.arange()` y `.reshape()`.
array_2d = np.arange(1, 10)
array_2d = array_2d.reshape(3, 3)
print("Array bidimensional de 3x3:\n ", array_2d)

# **Indexación en arrays** Extrae y muestra:
print(f"El primer y último elemento del array 1D: {array_1d[0]} {array_1d[-1]}")
print(f"El primer elemento de la primera fila del array 2D: {array_2d[0, 0]}")
print(f"El último elemento de la última fila del array 2D: {array_2d[-1, -1]}")
print(
    f"El elemento ubicado en la segunda fila y tercera columna del array 2D: {array_2d[1, 2]}"
)

# **Selección de filas y columnas** Extrae y muestra:
print(f"La primera fila completa del array 2D: {array_2d[0, :]}")
print(f"La segunda columna completa del array 2D: {array_2d[:, 1]}")

Array unidimensional del 1 al 10:  [ 1  2  3  4  5  6  7  8  9 10]
Array bidimensional de 3x3:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
El primer y último elemento del array 1D: 1 10
El primer elemento de la primera fila del array 2D: 1
El último elemento de la última fila del array 2D: 9
El elemento ubicado en la segunda fila y tercera columna del array 2D: 6
La primera fila completa del array 2D: [1 2 3]
La segunda columna completa del array 2D: [2 5 8]
