- 4. Explorando una imagen en formato de Array 3D
    
    En este ejercicio, simularemos una imagen representada como un **array 3D** en NumPy. En procesamiento de imágenes, un array 3D suele representar una imagen con dimensiones `(altura, anchura, canales)`, donde los **canales** pueden ser **rojo (R), verde (G) y azul (B)** en imágenes a color.
    
    ### Tareas:
    
    1. **Creación del array 3D**
        - Genera un array 3D de tamaño **4x4x3** con valores aleatorios entre **0 y 255** para simular una imagen en formato RGB.
        - Usa `np.random.randint()` para generar valores enteros.
    2. **Indexación en el array 3D**
        - Extrae y muestra:
            - El primer píxel (posición `[0,0]`) con sus valores de color **(R, G, B)**.
            - El último píxel de la imagen (posición `[-1,-1]`).
            - El valor del canal rojo del píxel en la segunda fila y tercera columna.
    3. **Slicing en el array 3D**
        - Extrae y muestra:
            - Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB).
            - Solo los valores del canal azul para todos los píxeles de la imagen.
            - Un recorte central de la imagen, seleccionando las filas y columnas intermedias (por ejemplo, de la posición `[1:3, 1:3, :]`).

In [25]:
import numpy as np

# **Creación del array 3D**
array_3d = np.random.randint(0, 256, (4, 4, 3))
print(array_3d)

# **Indexación en el array 3D**
print(
    "El primer píxel (posición `[0,0]`) con sus valores de color (R, G, B): ",
    array_3d[0, 0, :],
)
print("El último píxel de la imagen (posición `[-1,-1]`): ", array_3d[-1, -1, :])
print(
    "El valor del canal rojo del píxel en la segunda fila y tercera columna: ",
    array_3d[:, 1, 2],
)

# **Slicing en el array 3D**
print(
    "Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB):\n ",
    array_3d[:, 0, :],
)
print(
    "Solo los valores del canal azul para todos los píxeles de la imagen:\n ",
    array_3d[:, :, 2],
)
print(
    "Un recorte central de la imagen, seleccionando las filas y columnas intermedias (por ejemplo, de la posición `[1:3, 1:3, :]`):\n ",
    array_3d[:, 1:3, :],
)

[[[104  44 209]
  [231  78 110]
  [237 223 201]
  [118  17 127]]

 [[248   8  39]
  [ 71 176 150]
  [ 35 151   1]
  [138 120  31]]

 [[ 85 147 181]
  [251   7 225]
  [ 77 160 181]
  [ 87 142 182]]

 [[159  40  59]
  [ 84 238  37]
  [ 74 109 177]
  [109  96   2]]]
El primer píxel (posición `[0,0]`) con sus valores de color (R, G, B):  [104  44 209]
El último píxel de la imagen (posición `[-1,-1]`):  [109  96   2]
El valor del canal rojo del píxel en la segunda fila y tercera columna:  [110 150 225  37]
Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB):
  [[104  44 209]
 [248   8  39]
 [ 85 147 181]
 [159  40  59]]
Solo los valores del canal azul para todos los píxeles de la imagen:
  [[209 110 201 127]
 [ 39 150   1  31]
 [181 225 181 182]
 [ 59  37 177   2]]
Un recorte central de la imagen, seleccionando las filas y columnas intermedias (por ejemplo, de la posición `[1:3, 1:3, :]`):
  [[[231  78 110]
  [237 223 201]]

 [[ 71 176 150]