- 9. Normalización de datos con la norma L2 en rendimiento deportivo
    
    ### **Contexto**
    
    Eres un analista de rendimiento deportivo y tienes un equipo de **fútbol** que ha jugado **una temporada completa**. Para evaluar a cada jugador, has recopilado sus estadísticas en diferentes categorías:
    
    - **Goles marcados**
    - **Asistencias**
    - **Pases completados**
    - **Regates exitosos**
    - **Tiros a puerta**
    
    Sin embargo, los valores en cada categoría tienen escalas diferentes, por lo que es difícil comparar directamente el desempeño de los jugadores. Para resolver este problema, aplicarás la **normalización con la norma L2**, lo que permitirá convertir todas las estadísticas a una escala comparable.
    
    ### **Objetivo del ejercicio**
    
    1. Representar el rendimiento de los jugadores como una matriz en NumPy.
    2. Aplicar la **normalización L2** a cada jugador para escalar sus valores entre 0 y 1 mientras se mantiene la proporción relativa.
    3. Comparar los jugadores después de la normalización.
    
    ### **Datos de entrada**
    
    Supongamos que tenemos los datos de 5 jugadores:
    
    | Jugador | Goles | Asistencias | Pases | Regates | Tiros a puerta |
    | --- | --- | --- | --- | --- | --- |
    | Jugador 1 | 10 | 7 | 300 | 25 | 40 |
    | Jugador 2 | 15 | 10 | 250 | 30 | 50 |
    | Jugador 3 | 5 | 12 | 280 | 20 | 35 |
    | Jugador 4 | 8 | 6 | 310 | 15 | 38 |
    | Jugador 5 | 12 | 9 | 270 | 28 | 45 |
    
    Cada jugador es un **vector** con 5 componentes. Aplicaremos la **norma L2** para normalizar sus estadísticas.
    
    ### **Tareas**
    
    1. Representar los datos como una matriz en NumPy.
    2. Aplicar la normalización L2 a cada jugador (por filas, usando `axis=1`).
    3. Mostrar los valores normalizados y analizar cómo se comparan los jugadores tras la normalización.
    
    ### Preguntas
    
    - ¿Cómo cambian los valores después de la normalización?<br>
    Establecen un rango entre 0 y 1 el cual se adapta una escala que se define en función de los valores en el vector.
    - ¿Por qué la normalización L2 es útil cuando los datos tienen escalas diferentes? <br>
    Es útil para entrenar nuestros modelos de IA y evitar que nuestro modelo de mas peso a características que tengan modelos mas altos.
    - ¿Qué pasaría si normalizamos por **columnas (axis=0)** en lugar de por filas? <br>
    Aplicariamos una normalización por característica y no por jugadores, lo cual sería útil cuando queramos medir rendimentos específicos de cierto campo y no rendimientos globales.

In [9]:
import numpy as np

# Datos de entrada
jugadores = np.array(
    [
        [10, 7, 300, 25, 40],
        [15, 10, 250, 30, 50],
        [5, 12, 280, 20, 35],
        [8, 6, 310, 15, 38],
        [12, 9, 270, 28, 45]
    ]
)
# Normalizar el vector jugadores 
jugadores_normalizado = jugadores / np.linalg.norm(jugadores)
print("Jugadores normalizados:\n ", jugadores_normalizado)

Jugadores normalizados:
  [[0.01556817 0.01089772 0.46704502 0.03892042 0.06227267]
 [0.02335225 0.01556817 0.38920419 0.0467045  0.07784084]
 [0.00778408 0.0186818  0.43590869 0.03113633 0.05448859]
 [0.01245453 0.0093409  0.48261319 0.02335225 0.05915904]
 [0.0186818  0.01401135 0.42034052 0.04359087 0.07005675]]
